# Generated by Django 5.1.7 on 2025-03-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretSantaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='secret_santa.employee')),
                ('secret_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='secret_santa.employee')),
            ],
            options={
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
